server:
  port: 7072
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: Vercasm-JSON-inserter-service #TODO: rename to 'Vercasm-ingest-engine' and make consistent
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}
        service-Name: ${spring.application.name}
        healthCheckPath: ${management.server.servlet.context-path}/health
        healthCheckInterval: 15s
  logging:
    file:
      name: "mysomeapplication.log"
    level:
      org.hibernate.SQL: debug

  datasource:
   driver-class-name: org.postgresql.Driver
   password: colonial
   url: jdbc:postgresql://localhost:5433/Vercasm_Utils
   username: postgres
  jpa:
    hibernate:
      ddl_auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
