server:
  port: 7072
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: Vercasm-JSON-inserter-service #TODO: rename to 'Vercasm-ingest-engine' and make consistent
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}
        service-Name: ${spring.application.name}
        healthCheckPath: ${management.server.servlet.context-path}/health
        healthCheckInterval: 15s
  logging:
    file:
      name: "mysomeapplication.log"
    level:
      org.hibernate.SQL: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
