### This is the productions settings file, use parts of it to create your own 'application-dev.yml' file in this directory.
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: colonial
    url: jdbc:postgresql://localhost:5432/Vercasm_Utils
    username: postgres
  jpa:
   show-sql: true
   hibernate:
     ddl_auto: validate
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true